apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: v1.4.3
spec:
  image: fluent/fluent-bit:1.4.3
  positionDB:
    emptyDir: {}
  fluentBitConfigName: fluent-bit-config

