apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-docker
  #namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    memBufLimit: 5MB
    parser: docker
    path: /var/log/containers/*.log
    tag: kube.*
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-ubuntu
  #namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    memBufLimit: 5MB
    parser: syslog-rfc5424
    path: /var/log/syslog
    tag: syslog.*
---
apiVersion: logging.kubesphere.io/v1alpha2
kind: Input
metadata:
  name: input-centos
  #namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    bufferChunkSize: 1M
    bufferMaxSize: 1M
    memBufLimit: 5MB
    parser: syslog-rfc5424
    path: /var/log/messages
    tag: syslog.*