apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: stdout
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.2.0
spec:
  match: "*"
  stdout: {}